---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --audit-level=moderate

  - name: install
    image: node:12
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  #- name: test
  #  image: node:12
  #  commands:
  #    - npm test

  #- name: check-coverage
  #  image: node:12
  #  commands:
  #    - npm run check-coverage

  - name: build
    image: node:12
    commands:
      - npm run build
      - NPM_CONFIG_IGNORE_SCRIPTS=true npm ci --production

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: docker 
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/datastore-dump-harvester
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data: D4KbsiqoAuYeXkIDvXqleXIa8OPKQz5rSpctSTCXeStzmDAiTg8B4v/tnsBxGzYyI2Q=
---
kind: secret
name: docker_password
data: TdJP3GdkQI94m7VZh2geMB+a4uusUWTrJJJMQIK325Hw5S6jsB7jP/98UvdeWYIvmWaBqSqA9WqT/74l3WTBLCqd2F3YJD7gaRfVZYhyL/GjlomVCn3OpIHP1u8=
---
kind: secret
name: ssh_key
data: AYlSiKxQGQbymYi8Q4soCRWPV1Ok32H4n27TDN23HneIU+8NLMYs131j9Jx0uaTqpKxk0EohBgvYZBrOc6wkhXsamCgF2HaxlXhbsV+JD48y1zo3mbH4im35xy83Shu/Io6qB2QtpNTOE18DcVrjp18NZN3pZPPv+CwE22H7W4QRUSBWdLtMxetwDlVGfhIN64nQfcvr7Z7tqtQ1n23xhc3eKm+o8lW+zDQMp99Dchm60I2JnjidFbTX3CEkJ71cq6m2SqcIRMi66URKpT+MaZgMygEqsXYnWYqVZwPRBlTdCzAuZAQsIHL5+Gt+4UOWu3Bm78NcJpBpKSKH189sVNQZSNBa7xoIPQGz6fygWYhTeVuyhUO4Dq9rQ5A4fsoNLl9eRjH8cL6Pfx1DtKblmG81x1PiBvSTsCLClxUnDuB4M3YzV7aOyUpVCx1J4F3QWDD63vE7iZDriiOcPJHP33Cvp7QM/NlBTeyC7YOa1h6xGd9uZ6jJDqi8iI5aGtPdfnsfU7jocWdePG45M27FYqpHTCvuAOJoop07DjysqwwLNI+K0xR6ypWWnzviM7loxv0NGzFeImIJXHrXXSDDLBfgN7++Ujb1StO0nd0ob7HJYtSusIyaNpzCVT08QWB15IkVIad5laZmuJQaEaalCAU/oMB76K6/EpTB8u0E8ayeUiS5i4HfVMaw2uplSbAcPUc/0vDnnXo+JuRZIRc8GILwinxvuYbBrt9rkbyGLy+Sy3cwuj8qbAfNF3drvbyGsV0mNFIvWR2LwFFxZk9vvrODZKnkQpleYoNzHbgSzsgitVzHag0DAffirM8XteEDb249hwOFRKjzvZw5CljYmHF8el+nNmy/eEnbeC7rWUXdjUmBokrzGrACA524OkAdXiRnx6VBDi000rGr1ZoQ8Sna4ySTxobpV/FHgargzjdoiSAWFLJhfnscueOt1VGgE7qMRHu9lgJdtfREJN96erATWtXLwHD3AoPklhhF014oj8JU6U+m4ns9jBKiYc4vMt4tFLiOGkhwno+eqZZU6LbwkRRdE4PE8vAJeggNj/gxUa6Pnpc9Jw0HMFb/7lR0sjVA/kXXJmGZ2BpyzJ77Yv2RNO6KASSw52n5viY5H2qT1GlHQugcAW2L57Nk7+CEMUeXhjw2EFZ4i/999XKkL+HMJTICG+edlP9rd1sL6CHfvTq2JWvOxd1lVsLpWLJJPCbKPMVaSTI43yeMwQfV95W+KzNQMJVO3dg697iWO7xTzkmuCnTZ579EKN0h7Nm9Fc8dAZYrr+kRbu8X5dX6DMewQJJkzuo12KJcnUAcUFatuq6MCczlHgcpk0vWTNSKZAqqioMz3tfAc372Vi/8soMLk+5vromwxm4+MuDrDTkZW8/aEf3MNI2AmMMzNjCmq3Q3cDxcPNvcwL+4587qrsYeV0sZwPnc8gC85P3CDnmYog6VZH2BAYLQjyJapfLkpnOnMK3/X+ZndTf0N6U6Y08KWB8YlH2qsz9mnuzy8rw/ZLyOK9MGjz6+Bs5EsRNt+D+6m0HXJhZ6xSmDAipGKt6yRrtzZzDC/rXvirhuW+mxXTOeq+PusaO53Wm3ssKoYIoI9OANe0WBOMZiWHGaZ/WPReO/sYOZwkB+dWRRTj+w+lfizECAKSyd6KvgYQwt/aZjfDID659UYXEvw9H/kFnyJUVrszZQ/jI9MMO8ntG7ofW4CEZt5f6/MMzinhNXM/+7uE7OUp5S2zzzBQJQsF1BCvr7sctsktAaMyvY+mquPJ+jAGt8unqrP5ElLmXl2eDLiXwJUPGE6cuDi3MmJDI1T7vKwTGiJot4jP50gg0B4hZQPdnRDuYWPrB/AcV3WT6Cju4M/KePRRQkAYKnqSL7HLM221cfbuLVgtsikSaaKyWscK3pURDW5hEcID1q7ediljo6nQfXVpuQm5pKUP0tz59v/QV3JpCnyC5hsBuT+7UIL2jyuY6wxbmex7+PKtQNtLq4JQ9uPL+TbfJ0YqLFFKr/ICW3+/mn7dwg5L8I3Ya6b8M9YbAQP/l3AZlPjbRKID0Jwx5nUfRJxl0hQKjqKRZ+OVtp8QMyfVWFV1+L3WxkFZcRqtLjuWiI7QMQfc9qcvYQcuomXkxiy1kCznlU3zn7ATe7OYq4up7r6a/rgs9cAs3ztU3iaOaUkkCWkm/a0P2fSSGbBAZrkpqmusYiKi+YF7/JIVvDzo/MSm+bTrhtcxDKqJmIbmeu4zrURxvFgOo74E3ug1e/x0zpf5IEYh9wLzkHdDSo4MrlUYN9VppvKqOe9rVzHFM/S1s4ym/pPhR4UWFr9imfmb1ldBZ9YvJYW7K3U/QW8WAxqyQzYIGVGYOTsKrsRywvMc8gwQxsky+L1870UnRqkQHwU/KrUlnwaX/So9kMsEPX9SLhhoANjfLG28TEHu5r1+hnnsz6Ob2YyWrPYxf2vGUZHA+TcsYhK18/GOVkJOigTOV9dWwrnUEr38lzpEQhVOU2y2tsTyHtSmWGZqYJAuMBKCOnNBU9VBiRDTyT88KxFSVG16HxDsFNYHzUwo8MHugv1I9fjE+SFZ0vfaLlRD5ref4aNd6ogmyjHHscCcD6fzEzmAQ95u+HZEafnjxTMgwcWz5BbD7FWujYhBRLsYXat4bIGb/2ZMZeCmmftNHT+zMpaS4w2MwDH6Skh1PzmlXmC4lLPD3uXMUlSw5MkHAqPwxz9HgOB+86SnOGJ0pttUAeqHkjPsG+IA0grUQ3iSVENaAW/UoYpoBJNuhRYIsx5SSKRzu2CIWwDW7SXK9u8//V5dOQOe9jStoG54Ref0fr3NGVP/+QUM8P5m7GhgURGiSTfAKX+/Xnhi8ByL8J6LEuu4bt0V+zqmzDZruIm/XTooYaj6CcUYJ0MlZ7NnSYMRO+nYoFmTJ2HOGbmxwI1gmQ/MK8osgDcBcE9QJf/IkGCH3a5MhLktVaihPdEBHNHC1cwMuSfkCNq40YduKZErjFBLqjS2rUurvQHK8TbwYuZTvVxEcNjXS18hh1
---
kind: secret
name: gpg_key
data: 7UkWWN1mEcgDSGpq/m8idGov4Z2/NDxhNN5RfHou0FPnzArm0lH9HWThbSBfyIN1WtoQgrozgvGrtarc1defIH92TUM6lygcvcoGnNCehi9fdf4Zt3ZRfpSI/3LCsqOjq5+C15n/F4yVgdlH2cv7R4s4jz97za9GxKFPPpOkUh/YGq2dhPu68NVGB9VDIge5Jl8X/rXb1SlThaej4DIedanZKcE8S7lROtI9kmrGw9XXsWgU7ahdmPTzCrnoVnx/PYZ+bTji6F5rLZXa029Mgb2LNjsmru31BwtlZwke3xuSjQp8Pvagf0sD1pDgMFrUPatHySCDZumZ76AMQ8BkVxaKwXSWbnbQs5aCAe3YgmezUwowUF7K/TPgg4ZZA1dPQG/HLZa+qTMrLs9x+EFOvH+XhSzS6bhlPoT9pKbkD7Ffd8OZYMXl6myTBYmP2b/ylnm+djOrv4TSza5/vHnfd4YM+REOi4U0zAUmmMysUKWT6HW9+zLQWr1A//+LjnUCX4E6a3JkSZT/EsBroY3p987QjPf3ikR1RqtllTMYoYw4DGOS8vUpZa69kipSBfr13sPhCBXNomALEYaMFiokX1H3UAqlAaMfCwnyNn8JcktuAKl+530PT+Ij2DnEdJnb8KKZI4EoaYyA9lNvW5BB6M3LaevxFj59ON8e7DqJwOz2QM/sWb+maQls4MxJos936VubHyf4safwNz7iY5dKKbRzyGJ+R1gHYUIHpCS3synNPqrc3gFlzFMmISLJAKosHfzlOR9uYLHr+UqYLGl/tTgtiN6cXoeCFn280+wWqDSyURqUnzmM52acTpVy7GhbzGypFWs+SfE/eBlqHPdFO6T6rtyzysJ9mg/Do8O6vsLgWKJggkYgKvvsm3WzhPyUUp2OmLc46IIcGv8viKRJdZPWLOI2dO/NW+JsGiJ7DicwsGbYY438TzcfPKSa0sWn6TMrd3dMxR0GYku48YadGt+RvEETBtDEAxToXphWgXve0NyLjJCmwF7ErOaqITqAiY2TDKiSMfUrW48XomVA5VIKEWYOOu9YTLLba5no5NcnTU+ZqCyZ6jfka8gOwoNOoQrqMZcu3rXN6HO09zTpks/nnPKiLeTpyhxDyLmn9waGsfEkTlFoeYxtlswRn/Z5e+bsv6fK0XZienyQ5gWM34TvCRvVWOcE4CJXoSKtJtI1OTdHD1H2MXuHSTlDRFgHXFYmPLBiwY+DiUdbQMYLQBGbVXWPxxmOdhNVHVBjofLuxAv8qyyvDaheZKaRrShsydfk37jyzRKWQLkIEMY9ArL9eo718mG6fUsGdTKYM77ZtojB6S9T4+gfysWp7crhJq63OR8Q0r1CFW99aqwesHaczwpjvD2Vc1lXdtYfur3AH0HgUkISl0k5lOfRmMwWkX69/bnpCWFvu79yWujcPqTyio0HXWMNgcJBS7IgmEyblYdT94r+Mwj9ajtfZ4KXe2tFIErhRnCG/SsxBakMORwnAl9K9NiefIVnkijuETgUrZJkUhXHb8bPmLuTvqilLj8d0QR8ocNajdC3oveLC7eAuvI9bH2Cz+QLi0lBFzc5SHQAKYssB66M1ZewbebkughBU7jdhXK8bS5+U/k+Jn7Nxha2WisjYKnSmkRZ6KRA7vNk7hHpsxJG+ju0R15sIhBoW0oe5v4pAy6aPza6t+/D3AiKZkmGKThxx6db0RlM2hchG6QOkV78EFv5chAWJXTr+KKi9Qa22j/ePi7illQ3kA7tTW7XKDhTLJ8ar6INEHYuuQvXreZxwQxHR1GVus9CH7vz7foOOyQnqsOSUNEGHVHD3xlB5lyT3z4DJnB9OhRI62ikYbNtZoJwdJrI3Jw6XQjyzdjL8KdEGKaJDGMqmNPRAuB0n2NXYRMpJL2VChjHK7WZBzWwmUUFGL9BIYXiEn7K6brkYyHBS47f88p98B8g+b5ORho9q4LMOLbY5eUc/ZkPfNz+CCsANJBYzhPTzcXpdkGc5K2gCP9xAi0MWADd87f+qhnCaGGVOpOS9k75jWnzPeMqn6ZGwLVSvQg42lO0iWqWpyiRN5vkUI2ZaQOCnyzq+MUdLe3ZWG5xfwrR0ZyRqxmdglkKQuris4h8NSt6vDFaNKB8LBsrOT29ATaNmDN5ZhYDII58SgPp7v8JJjZHgLBXsBWMyq/Fsanct1nC7N+Txk5EIvJdsYdC4BE5FPxA97qt76fpRYkwdboHurV/l1Yf6wMoCZF7s/87s7nV+xnli4o6hYc5NRA4Sd8O4nqVDUbWTQl/OkQ5kVww7fpn1KiUkZ9ZvwcSs11Fstk0ovDRgk5kfvP6MIqwFC2btmmc1zy5jQ5bh3+0uyu+i/Cda0naQINBvLEhBBpCB3ah/7qd0PcRaSr1ijzKduLwuxWaffxvs9alk3B4kkE+iWOntszwHjrFqSLh0nLDGXzDVSpz46soDxbqr2M1+bn7RKJ2wl4Pu+Z9YLmE/iW1kptcRoSRkUL/lIM5nt7HMaxM9ksE0gcvfjnY2JicOyxHszSTP3Oy/6D2beAvQkW0+DfcO9efZwxzBX8Z2ctu7VzpzZxe2AztkTG6CUwsXaTSgodqkVwsZaCATj2g/fcGXSbHRmQ/crdoYEWIFd84lEKwCuZ2KzdCq7vJ8dWYFZyN9+09Wf1b9GFB1mtxwvjSBvX3tqE1G61QOuRqr0TplrQFONNEELxJXrxGgSND48jWuqSJBhRfOs12W/NC3OaGYKSNL0nfIZ66DG7iLeR/BFrYBP9iLEhiYUXnboxrZoB7q+PG2QOfaHLD86GZbjkpuRbQ4F4mM20yVbYZNBY76zm1mxDxx1MB0Z1NfqcXwV8OLpKlO1Srmm0azW9wtL9rZLMrn9u9ZXmeybUf8MmjTxTuPCj07279P87HgkFx00K/y5526RiKtAVQ0c2dEPGbYSN6HIAFXBHPVsJfUHIgBaH/+OHLABQBdNRZhwjfw2r6RXMpGsXTLvRQL/DMhYOvVoXxAljOdveM7bqR+aZFXhVSc1l5TAo0RbPvq5UKlDF70WVvXCDgU2j6NwnR043ugk7oTc7y7PsxDZUmdfV/yo0xCclPtxR2t8Qgc9d/0mbreAzFrtmcL5ZVTylhuRnrm4n3CDL/MIPaQPrAvXe0W7EFlBQ5SsoE6BtgCoh9pX7Hu7sm+WRZfLzzWi6rkYlNoNct9sd58IGyOzULHTTLQP4P8KCaW0g4+cs4OzcoYsKfjLR/dv5vmSr4D8zwZDtLKZNyeRT27dnrdJYUQV3JtgtufyOEtXxEtyWvrFLC9XbIwsnC/255OT5J3rVmDDhrOXfHdqJphw2nhzPyDUL9Xor+Da4JawY4E+6TQlKf7eHQR6AO5M76Ewmsz29TmyypyXDL3LEwKaJPFAAHkpDOdrLJ5TH5JQ+cUgAVQsyZ2FoIuilq8yl25oZDULIu2jEL07RCgZlKfYU8QMXw1Iv5ltnZUXcTwQBU4S/uhCF0S+3+RqapYrepWFCD8Fo71CwwCTyxymY913JwJCYGBLo+OjKQ+H15DgnLXn1i9L+h4hNxB5Ln90qjbhMv1Ty0dNtAV5YKjs8B5gp3Iw+f5tpPwVSSffQyUB3BzWRNxWYl9OpsfjMkQcfuAXOQ2yNukYJq6uD978dApJHV2AK3OrEFG8sHl9c2HHcNFAHUux71Yssi/RB0OdkXnrPNqbw1aN4N7ecAkv8nMkh+RZdoBBGXphwiW2FA6gVz3vezPvcvwq/59u+oKvw/w/OyjehnE04AQVFgKXOYy9aKpit08axNqgBDJMqAhH43v7BdW1mNEIu3yG1ZlWC0deI6sodA6qlWN0CT/JbFD0NJ3E8nq3d2X4Ds3hUBJxWNFr21iliOUVa/cYCHYJT5iL+V6pso9XPkhKIA7+Y3QUyJJ92iiuetSZe4QNZUGn5KT0Lxni9WbhR9F/CcF5Qb4g7c9xWp/DWmqVM6CHJ/H3vS+I1frX6JPvzUF/ZS5V3ybTvMRv3ktofnn2WZ/A9HjRwk65tmEBZZl0afkcvzhwU5AniB4KBc27/oOR9WBB67S+tq64zLyU92RS33l5dSm1hDQNkdVBu18S5nj2oRKorxpr51wvUFdNapMoGh8dgIU19bkMlujBBUSZx4hXZGVRX+OaXa2BPBXQ4cVk+9ZNeyn1PahOpzVapqnCyOOaDgdA70gCR/wIJKLzD3gnl4IK70M112uoCRBmeu329TtmGB/nVhWBqA3KvvSf2ZZAmpxifxXysuyHRuPRQXjbkRPngpgSBCqgYk7v0n3QOfOVfZiqryxBU07pCrO6kNQ+dNHmanm4zS7taMJs0BQX1h2Bbo12xKLjtdhXiQNv/N3JQg3d6pTOUu8GvoJmpibdNfm8T09OKp2D1b4egmoO+YrIbRFmc0sk66Z+GM3Vz1ADxFDJKPLK2P2H7sMljtGi4dE1yGxRKBYJTn7VFdV/+NAtGUgbfC/iZ/3pVYCb8LhHZkgn15rAHuuHnQFdeItWiU3SzHKzKHWwsMkhHPcI5k4bPKhILZs07aRG0lBu14KSO6kbPAo0uiKf3o5hMjLUONe6+OtupO5pQBAWYCvuADaj6wVCU6ODCgqLhausauXAfrUyVQf1aCYGUuBrQJ0p03lqQe+yCbZN+tYaqYx4C/1bTBswMheQb4cJZY1IdnNw+1JKctvnKlT6+raB1bwfdFVLs0o2DCvQ/CZM5QN18GrFLoA4qP7GWkBDtsSsgeeRd9ugg574ashm1ppkwonpqcl7p4c5aqLU8Ic4FfA7/4Q55qMMHcNlaHxobe67wL4TcxuHXXMbpkiy5M2IHUlMy4H8yMRN2nx/1s3g1zkwrP3sk1tx+gbQFIbGBoFWNe94x7SFtDXdZx5IpkF/gouuAEip2tRS2cAVx3dzX8dD4OknIB4i46HCusLi96Cn6xICStYIM2Gh8dMmWb3+cQ2mtN35+H61h1UmPgTIAh7UtMylItw89iK1dHE8pxc8uDet5JnY8n60Pj2GfJc9ZUxXtb0E04CpVl0TCCe9wno8EAwVCcZ4nQLcEHz4OyM/dqMuaq8c8whC1O+ZQzEiAlTUsyrfoD/BZ4WEBkVjerN1l+0PptXiIng4qXRa2A1MPLVj3C6oQkZsNQejAcJpnoh3N62UMcrSF3B/zQcWB/IptpwoZCjtfAeeIEQ1p1gpQP2kcGD2QdT2cOx2jp5MzL/We/GmJrlhqwslxcK6eGS6QQzRXMGhyIje6iHayezl5t+L50D0WvwlS7SqEyNrdteO1wovkwOvyfW7RZHzOw3e2pINQ3rGv9Y4oYZQDTbpWhy7uKv4PVTXfG1IV19dOUJwiMLALyJqw7Go5hpSjvAirzGMfeV4CHKqyAsWEDTMNmlEh8rQ2vlXiQAF+MewHTJOFDPcWTEtEhwWzD+7PdZn43utzWMp5D5QJazjwXXwOnwkYu9itWidofexZ2K/S4nR5hbPB4JfKIm+ZfBovFFQLXHfXj6FoMiz/asIAoDCenOqemrGeUor/efMR4LAAb1vTm0c98y3gfEMJ26QTYApSz/So6tlGN4O6jHAwj8O+qHCVPPsi7O3Ulzztx1qfY34j2EsDCBxadIrt8SxErrmRjjxHdhcbv9+whLgMXmqYUIp+VTjdrMBAFs/vVKrTKwR0lyB9rTRV4ooP6oYL4tWEx9yJ/HdzJ/rnSbYgjutcF2uLoBEeuodMEtGJJ+vduuI5HNObmo2z8UTxJkXyJro5kdglefouIcY2dETy5ICXjhBneiGUYLWKhgSQ3TJ1+ODfj+7HCkTImL4H24fdgSEwCFNn52YHdPSqJXIEqvseXG58zepquCBFny2nPopM10TOC2VbXcVV5guwiQPN7xJTe2hTSCCQJzuvKFoTQTr3SOSF8OgVxQnF9K4ksz34GGFZPxzVIvGURgxLOClVKArfK7gek2NSQ38dyMyZx0nXVo9CClp0reFf26rezHM/LtEMI8Wh+ezjgrzgGxkGeHe0tKaZPHDf65zb4fFiK4KjI5LHAeHIKJb4DDDuAbgXTTH4dJN7C6lTcrVjqfzylG3ZONwbQrJ1QBLcAtxdsktqoT61ZmOqgSC3R3FBrtlNcSjXGZwTARYJrM0nG/n5PlYWwpTUxh0B7RIW2WM2C7ok8ggR1fwyQlcIQ59FaJ+SRICjccEVE4R5dLwzoObqeDrzmhC39y9edBjGeVmXIax6CLWPs6d8+cD2Fqho03VHYDV0NiNRF2BsC0v1dxO1UMzWJzw3DpOsfXsHoUKtyVvZmNof1570jYC43/Kzcc+12q/dZ8STkPntJZRD+PY2TOJr39SbFQMUxszVriITp8JQfmp/Yh0+1XbijoMyY3HiwzJt2K4uKvDfpjEKj3XAlkZHHUDvLnTb1m9INpEwfi45OB+aqjrzUXcjXxtXo3/I51HZc2cWqVMP7LR8K4DgLsOsNqLOBoiAT5tlACN7tKhg5wjUtHNjNt9Gqyst3k5MHE6iIDAG/FqjaPV2f2GqqbD+ZFWWrkxiWn1P+/TEyLDCBlahbK0e38R7h6vLgMqKQXLiPUzFfWmuCtAwrYmjzq+hmjV5dDfpJofigQVomhqWm2QNsuF2U7NaIp0wWtP1E8kDaf+4J0Yw5gARMSbKhQ+BkY0l0HY3DTQ2jkovoWzStbyKVHBwBqs197dlPm4mkgalKpDjZVVuoILBPW/ghuLvb4/YarADePlFauI5YfQ==
---
kind: signature
hmac: 6b04cb862b51a40f9bdc160a51dd3df864009885a77668d595166a4db91eb4fb

...
